### ISSUE TITLE
check_win_ms_updates not working on Windows 10 for Nagios

### ISSUE THREAD

**Issue by trgrassijr55** [PowerShell/xWindowsUpdate#50] opened 2017-02-24 00:53 UTC
My command
define command{
        command_name    check_ms_win_updates2
        command_line    $USER1$/check_nrpe -H $HOSTADDRESS$ -t 60 -c check_ms_win_updates -a '-wd 45 -cd 90 -M PSWindowsUpdate'
}

My service
define service{
        use                     generic-service
        host_name               TGKW001
        service_description     WSUS
        check_command           check_ms_win_updates2
        servicegroups           Windows Updates
        }
Part of my nsclient

; Section for external scripts configuration options (CheckExternalScripts).
[/settings/external scripts]

; COMMAND TIMEOUT - The maximum time in seconds that a command can execute. (if more then this execution will be aborted). NOTICE this only affects external commands not internal ones.
timeout = 60

; COMMAND ALLOW NASTY META CHARS - This option determines whether or not the we will allow clients to specify nasty (as in |`&><'"\[]{}) characters in arguments.
allow nasty characters = 0

; COMMAND ARGUMENT PROCESSING - This option determines whether or not the we will allow clients to specify arguments to commands that are executed.
; allow arguments = 0
allow arguments = 1
; A list of scripts available to run from the CheckExternalScripts module. Syntax is: <command>=<script> <arguments>
[/settings/external scripts/scripts]

check_ms_win_updates = cmd /c echo scripts/powershell/check_ms_win_updates.ps1 $ARG1$; exit $LastExitCode | powershell.exe -command -

Now I ran it from Powershell v5 on my Windows 10 Pro computer 

PS C:\program files\nsclient++\scripts\powershell> .\check_ms_win_updates.ps1 -M PSWindowsUpdate
CRITICAL: Last successful update at 2016/01/13 18:26:22 exceeded critical threshold of 150 days. Pending updates {Total:

It takes a very long time to run 15 20 minutes.

It does not think it is up to date either this Windows 10 machine is current with updates.

I have it working on Windows 7 machines Windows 2012 
Trying Windows 2008 soon

Any ideas

Thank you 

Tom

**Comment by JHenneBiomed** [comment] 2017-03-29 02:13
Hello, it looks like you are using the PSWindowsUpdate module not the xWindowsUpdate resource. The PSWindowsUpdate module is using the Windows Update Agent (WUA) api. Unfortunately I have no experience with Nagios but it seems like the issue is more with the usage of PSWindowsUpdate. You may need to determine what service WUA is pointing to when looking for updates - because you may see more updates returned if the Microsoft Update service is used instead of Windows Update. Add some verbose or debug output to your script to get a feel of what it is doing. When you check for updates within your script are you also downloading the updates? Try adjusting some of the parameters used with the PSwindowsUpdate cmdlets and see what happens. Or try the WUA Api directly by making COMObjects. I did find a couple of forum responses where people were experiencing slowdown with WUA:

http://stackoverflow.com/questions/27337433/slow-wua-windows-update-api

https://www.quora.com/Why-do-Windows-updates-take-so-long-to-check-for

The PSWindowsUpdate project page can be found here: https://gallery.technet.microsoft.com/scriptcenter/2d191bcd-3308-4edd-9de2-88dff796b0bc

**Comment by johlju** [comment] 2018-05-07 12:21
Closing this as this seem to not be about this resource module.

**Closed as completed by johlju** 2018-05-07 12:21 UTC
Labels: external
